project:
  type: book
  output-dir: docs
execute: 
  #echo: false
  warning: false
#filters: 
  #- webr
  #- abstract-section:
book:
  title: "Artigo à Prova de Futuro"
  subtitle: "Jornada de Open Science na Prática"
  #author: "Pablo Rogers"
  #date: last-modified
  #date-format: long
  #doi: 10.5281/zenodo.10443128
  cover-image: img/cover.png
  downloads: pdf
  reader-mode: true
  sidebar:
    align: left
    collapse-level: 1
  page-footer:
    left: <a href="https://www.phdpablo.com">by Pablo Rogers</a>
    right: This course was built with ❤️ and <a href="https://quarto.org/">Quarto</a> 
  site-url: "https://phdpablo.github.io/curso-open-science/"
  repo-url: "https://github.com/phdpablo/curso-open-science/"
  #repo-actions: [edit,issue]
  sharing: [twitter, facebook, linkedin]
  open-graph: true
  
  chapters:
    - index.qmd
    - 00-prework.qmd
    - 00-schedule.qmd
    - 01-intro.qmd
    - 02-osf.qmd
    - 03-zotero.qmd
    - 04-project.qmd
    - 05-git.qmd
    - 06-quarto.qmd
    - 07-docker.qmd
    - 08-AI.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    title-block-style: none
    toc: true
    collapse: true
    html-math-method: mathjax
    #include-in-header: header-includes.html
    #css: style.css
    #code-link: true
    theme:
      light: flatly
      dark: darkly
    number-sections: true
    link-external-newwindow: true
    fig-width: 5
    fig-height: 5
    fig-align: left
  
  pdf:
    documentclass: article
    papersize: A4
    #abstract: "Working in progress"
    top-level-division: section
    #code-block-bg: gray
    geometry:
      - paperwidth=8.00in
      - paperheight=10.00in
      - left=1.25in
      - textwidth= 5.25in
      - top=1.00in
      - textheight=8.25in
      #- showframe
    #include-in-header: preamble.tex
    #include-before-body: first.tex
    #include-after-body: backcover.tex
    toc: false
    colorlinks: true
    fig-width: 5
    fig-height: 5
    fig-align: left
    keep-tex: true

editor: visual

